# -*- coding: utf-8 -*-
"""Copy of 2021-11-10_Gagandeep_Project24

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZxoiBN1RtaRL8pkx6G-pqB_J5htqMvZ

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

1. Cartograms using the Folium Module

---

### Activities

#### Activity 1: Mark the Statue of Liberty on Folium Map

Given the coordinates (40.6892, -74.0445) of **Statue of Liberty** in the **Liberty Island**, mark the location using a marker and also add a pop-up of the location on the Folium map.
"""

# Create a Statue of Liberty (coordinates 40.6892, -74.0445) map and add a marker for the same on the map.
import folium

statue_of_liberty_map=folium.Map(location=[40.6892,-74.0445],width='50%',height='40%',zoom_start=16)

folium.Marker(location=[40.6892,-74.0445],popup='Statue of Liberty').add_to(statue_of_liberty_map)
statue_of_liberty_map

"""---

#### Activity 2: Mark the **Marina Beach** with circular marker

Given the coordinates (13.0556, 80.2837) of **Marina Beach** which is the 2nd largest beach in the world located in Chennai. Mark the location with a circular marker and also add a pop-up of the location on the Folium map.
"""

# Create a Chennai map (coordinates 13.0556, 80.2837) and add a circular marker for the Marina Beach on the map.

chennai_map=folium.Map(location=[13.0556,80.2837],width='80%',height='60%',zoom_start=13)

folium.Circle(location=[13.0556,80.2837],popup='Marina Beach',color='#0000ff',fill=True,fill_color='#000fff',radius=800).add_to(chennai_map)
chennai_map

"""---

---
"""